### ISSUE TITLE
panic: proto: duplicate extension registered

### ISSUE THREAD

**Issue by hazcod** [temporalio/go-sdk#236]
As reported on https://temporalio.slack.com/archives/CTDTU3J4T/p1597225501187900
Conflict with temporal/api/dependencies/gogo.proto

## Expected Behavior
A run works fine.

## Actual Behavior
Go code (api + worker) fails on startup with following error
```
panic: proto: duplicate extension registered: descriptor.EnumOptions 62001

goroutine 1 [running]:
github.com/gogo/protobuf/proto.RegisterExtension(0x26e8620)
        /go/src/app/vendor/github.com/gogo/protobuf/proto/extensions.go:595 +0x2cb
github.com/gogo/protobuf/gogoproto.init.0()
        /go/src/app/vendor/github.com/gogo/protobuf/gogoproto/gogo.pb.go:709 +0x31
panic: proto: duplicate extension registered: descriptor.EnumOptions 62001
```

## Steps to Reproduce the Problem
go.mod:
```
	go.temporal.io/api v0.28.0
	go.temporal.io/sdk v0.28.2
```

## Specifications

  - Version: 0.28.0
  - Platform: docker

**Comment by hazcod** [comment]
Same issue with 0.29 for SDK, API and Docker.

**Comment by hazcod** [comment]
I see the same RegisterExtension calls in `gogo/protobuf/gogoproto` and `api/dependencies/gogoproto` ?
![image](https://user-images.githubusercontent.com/5222512/91126625-b55cbc00-e6a4-11ea-8a89-6c09a101b915.png)

**Comment by hazcod** [comment]
Seems to work if I manually comment out the `RegisterExtension` calls in vendor/github.com/gogo/protobuf/gogoproro

**Comment by hazcod** [comment]
Quote from alex:

you are on latest go 1.14, right? Everything is on by default there. just delete vendor dir and run go mod init and then go mod tidy

**Comment by hazcod** [comment]
@alexshtin i'm actually still stuck with this; I have private go dependencies that cannot be fetched during the Docker build, since that would embed SSH keys in the eventual image. (and docker squash support isn't widespread)
Also, the path of SSH keys on systems differ.

How would I make this work with private go dependencies? I need to prevent a `go build` to check online for dependency updates, which only seems to work with `vendor/`?

**Comment by hazcod** [comment]
@alexshtin I am now doing it the recommended GOPATH/pkg/mod way, but I still receive this error, which is weird.

Dockerfile:
```docker
COPY go.mod go.sum /go/src/app/
RUN if [ -n "$GITHUB_TOKEN" ]; then git config --global url."https://$GITHUB_TOKEN@github.com".insteadOf "https://github.com"; fi \
    && go mod download

COPY . /go/src/app/
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags '-w -s -extldflags "-static"' \
    -o /go/bin/api ./cmd/api/ \
    && chmod u=rx,g=,o= /go/bin/api
```

And log:
```
api_1         | panic: proto: duplicate extension registered: descriptor.EnumOptions 62001
api_1         | 
api_1         | goroutine 1 [running]:
api_1         | github.com/gogo/protobuf/proto.RegisterExtension(0x277e240)
api_1         |         /go/pkg/mod/github.com/gogo/protobuf@v1.3.1/proto/extensions.go:595 +0x2cb
api_1         | github.com/gogo/protobuf/gogoproto.init.0()
api_1         |         /go/pkg/mod/github.com/gogo/protobuf@v1.3.1/gogoproto/gogo.pb.go:709 +0x31
```

**Comment by hazcod** [comment]
Matches for `RegisterExtension` with `EnumOptions`:
```
/go/pkg/mod/github.com/cncf/udpa/go@v0.0.0-20191209042840-269d4d468f6f/udpa/annotations/migrate.pb.go:  ExtendedType:  (*descriptor.EnumOptions)(nil),
/go/pkg/mod/github.com/envoyproxy/protoc-gen-validate@v0.1.0/gogoproto/gogo.pb.go:      ExtendedType:  (*google_protobuf.EnumOptions)(nil),
/go/pkg/mod/github.com/envoyproxy/protoc-gen-validate@v0.1.0/gogoproto/gogo.pb.go:      ExtendedType:  (*google_protobuf.EnumOptions)(nil),
/go/pkg/mod/github.com/envoyproxy/protoc-gen-validate@v0.1.0/gogoproto/gogo.pb.go:      ExtendedType:  (*google_protobuf.EnumOptions)(nil),
/go/pkg/mod/github.com/envoyproxy/protoc-gen-validate@v0.1.0/gogoproto/gogo.pb.go:      ExtendedType:  (*google_protobuf.EnumOptions)(nil),
/go/pkg/mod/github.com/envoyproxy/protoc-gen-validate@v0.1.0/gogoproto/gogo.pb.go:      ExtendedType:  (*google_protobuf.EnumOptions)(nil),
/go/pkg/mod/github.com/gogo/protobuf@v1.3.1/gogoproto/gogo.pb.go:       ExtendedType:  (*descriptor.EnumOptions)(nil),
/go/pkg/mod/github.com/gogo/protobuf@v1.3.1/gogoproto/gogo.pb.go:       ExtendedType:  (*descriptor.EnumOptions)(nil),
/go/pkg/mod/github.com/gogo/protobuf@v1.3.1/gogoproto/gogo.pb.go:       ExtendedType:  (*descriptor.EnumOptions)(nil),
/go/pkg/mod/github.com/gogo/protobuf@v1.3.1/gogoproto/gogo.pb.go:       ExtendedType:  (*descriptor.EnumOptions)(nil),
/go/pkg/mod/github.com/gogo/protobuf@v1.3.1/gogoproto/gogo.pb.go:       ExtendedType:  (*descriptor.EnumOptions)(nil),
/go/pkg/mod/github.com/lyft/protoc-gen-validate@v0.0.13/gogoproto/gogo.pb.go:   ExtendedType:  (*google_protobuf.EnumOptions)(nil),
/go/pkg/mod/github.com/lyft/protoc-gen-validate@v0.0.13/gogoproto/gogo.pb.go:   ExtendedType:  (*google_protobuf.EnumOptions)(nil),
/go/pkg/mod/github.com/lyft/protoc-gen-validate@v0.0.13/gogoproto/gogo.pb.go:   ExtendedType:  (*google_protobuf.EnumOptions)(nil),
/go/pkg/mod/github.com/lyft/protoc-gen-validate@v0.0.13/gogoproto/gogo.pb.go:   ExtendedType:  (*google_protobuf.EnumOptions)(nil),
/go/pkg/mod/github.com/lyft/protoc-gen-validate@v0.0.13/gogoproto/gogo.pb.go:   ExtendedType:  (*google_protobuf.EnumOptions)(nil),
/go/pkg/mod/go.temporal.io/api@v0.29.0/dependencies/gogoproto/gogo.pb.go:       ExtendedType:  (*descriptor.EnumOptions)(nil),
/go/pkg/mod/go.temporal.io/api@v0.29.0/dependencies/gogoproto/gogo.pb.go:       ExtendedType:  (*descriptor.EnumOptions)(nil),
/go/pkg/mod/go.temporal.io/api@v0.29.0/dependencies/gogoproto/gogo.pb.go:       ExtendedType:  (*descriptor.EnumOptions)(nil),
/go/pkg/mod/go.temporal.io/api@v0.29.0/dependencies/gogoproto/gogo.pb.go:       ExtendedType:  (*descriptor.EnumOptions)(nil),
/go/pkg/mod/go.temporal.io/api@v0.29.0/dependencies/gogoproto/gogo.pb.go:       ExtendedType:  (*descriptor.EnumOptions)(nil),
/go/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/filetype/build.go:                              case "EnumOptions":
```

**Comment by hazcod** [comment]
Seems to be fixed with latest master commit hash @alexshtin , thank you.
I'll keep an eye on the next release.
